import * as fs from "fs";
import * as path from "path";

const badwordsPath = path.join(process.cwd(), "badwords.txt");
const outputPath = path.join(process.cwd(), "lib", "badwords-generated.ts");

const badwordsContent = fs.readFileSync(badwordsPath, "utf-8");
const badwords = badwordsContent
  .split("\n")
  .map((word) => word.trim())
  .filter((word) => word.length > 0)
  .map((word) => `"${word.replace(/"/g, '\\"')}"`)
  .join(",\n  ");

const output = `// This file is auto-generated from badwords.txt
// Do not edit this file directly. Edit badwords.txt and run: npm run generate-badwords

export const BAD_WORDS = [
  ${badwords}
] as const;

export type BadWord = typeof BAD_WORDS[number];
`;

fs.writeFileSync(outputPath, output, "utf-8");
console.log(
  `Generated ${badwords.split("\n").length} bad words in ${outputPath}`
);
